name: analysis

on:
    pull_request:
        types: [opened, synchronize, labeled, unlabeled]
    push:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    biome:
        name: biome ci
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Node + PNPM + install deps
              uses: ./.github/actions/setup

            - name: Run Biome Static Check
              run: pnpm biome ci .

    analyze:
        name: codeql
        runs-on: ubuntu-latest
        permissions:
            security-events: write
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Initialize CodeQL
              uses: github/codeql-action/init@v3
              with:
                  config-file: .github/codeql/codeql-config.yml

            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v3

    type-check:
        name: tsc
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            -   name: Checkout Code
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: Setup Node + PNPM + install deps
                uses: ./.github/actions/setup

            -   name: Run Type Check
                run: pnpm typecheck
